/* ===================================================================
   VOCABULAIRE — CORÉEN
   Pour ajouter un mot : copie une ligne et modifie fr / kr / cat.
   `jamo` est optionnel : décomposition syllabique affichée au survol.
=================================================================== */
const koreanData = [

  // ---------- Expressions & politesse ----------
  { cat: "Politesse", fr: "Désolé (formel)", kr: "죄송합니다" },
  { cat: "Politesse", fr: "Désolé (courant)", kr: "미안해요" },
  { cat: "Politesse", fr: "Désolé (informel)", kr: "미안해" },
  { cat: "Politesse", fr: "Merci (formel)", kr: "감사합니다" },
  { cat: "Politesse", fr: "Merci (courant)", kr: "고마워요" },
  { cat: "Politesse", fr: "Merci (informel)", kr: "고마워" },
  { cat: "Politesse", fr: "Merci (chaleureux)", kr: "고맙습니다" },
  { cat: "Politesse", fr: "S'il vous plaît (resto)", kr: "주세요" },
  { cat: "Politesse", fr: "S'il vous plaît (formel)", kr: "부탁드립니다" },
  { cat: "Politesse", fr: "S'il vous plaît (informel)", kr: "부탁해요" },
  { cat: "Politesse", fr: "Excusez-moi ! (appeler serveur)", kr: "여기요" },
  { cat: "Politesse", fr: "Je ne sais pas", kr: "몰라요" },

  // ---------- Connecteurs / Adverbes ----------
  { cat: "Connecteurs", fr: "Donc", kr: "그래서" },
  { cat: "Connecteurs", fr: "Un peu", kr: "조금" },
  { cat: "Connecteurs", fr: "Beaucoup", kr: "많이" },
  { cat: "Connecteurs", fr: "Trop / Très", kr: "너무" },
  { cat: "Connecteurs", fr: "Vraiment", kr: "진짜" },
  { cat: "Connecteurs", fr: "Mais / Par contre", kr: "그런데" },
  { cat: "Connecteurs", fr: "Et / Avec", kr: "하고" },

  // ---------- Mots interrogatifs ----------
  { cat: "Interrogatifs", fr: "Quoi", kr: "뭐" },
  { cat: "Interrogatifs", fr: "Qui", kr: "누구" },
  { cat: "Interrogatifs", fr: "Où", kr: "어디" },
  { cat: "Interrogatifs", fr: "Quand", kr: "언제" },
  { cat: "Interrogatifs", fr: "Pourquoi", kr: "왜" },
  { cat: "Interrogatifs", fr: "Comment", kr: "어떻게" },
  { cat: "Interrogatifs", fr: "Combien (quantité)", kr: "몇" },
  { cat: "Interrogatifs", fr: "Combien (prix)", kr: "얼마" },

  // ---------- Adjectifs ----------
  { cat: "Adjectifs", fr: "Être bien / bon", kr: "좋다" },
  { cat: "Adjectifs", fr: "Être délicieux", kr: "맛있다" },
  { cat: "Adjectifs", fr: "Être grand", kr: "크다" },
  { cat: "Adjectifs", fr: "Être petit", kr: "작다" },
  { cat: "Adjectifs", fr: "Être joli", kr: "예쁘다" },
  { cat: "Adjectifs", fr: "Être nombreux", kr: "많다" },
  { cat: "Adjectifs", fr: "Avoir / Exister", kr: "있다" },
  { cat: "Adjectifs", fr: "Ne pas avoir / ne pas exister", kr: "없다" },
  { cat: "Adjectifs", fr: "Être vide", kr: "고프다" },

  // ---------- Temps ----------
  { cat: "Temps", fr: "Aujourd'hui", kr: "오늘" },
  { cat: "Temps", fr: "Demain", kr: "내일" },
  { cat: "Temps", fr: "Hier", kr: "어제" },
  { cat: "Temps", fr: "Maintenant", kr: "지금" },
  { cat: "Temps", fr: "Week-end", kr: "주말" },
  { cat: "Temps", fr: "Matin", kr: "아침" },
  { cat: "Temps", fr: "Midi", kr: "점심" },
  { cat: "Temps", fr: "Soir", kr: "저녁" },

  // ---------- Lieux & Transports ----------
  { cat: "Lieux & Transports", fr: "Maison", kr: "집" },
  { cat: "Lieux & Transports", fr: "École", kr: "학교" },
  { cat: "Lieux & Transports", fr: "Restaurant", kr: "식당" },
  { cat: "Lieux & Transports", fr: "Magasin", kr: "가게" },
  { cat: "Lieux & Transports", fr: "Ville", kr: "도시" },
  { cat: "Lieux & Transports", fr: "Pays", kr: "나라" },
  { cat: "Lieux & Transports", fr: "Gare", kr: "기차역" },
  { cat: "Lieux & Transports", fr: "Aéroport", kr: "공항" },
  { cat: "Lieux & Transports", fr: "Hôpital", kr: "병원" },
  { cat: "Lieux & Transports", fr: "Banque", kr: "은행" },
  { cat: "Lieux & Transports", fr: "Poste", kr: "우체국" },
  { cat: "Lieux & Transports", fr: "Pharmacie", kr: "약국" },
  { cat: "Lieux & Transports", fr: "Bibliothèque", kr: "도서관" },
  { cat: "Lieux & Transports", fr: "Musée", kr: "박물관" },
  { cat: "Lieux & Transports", fr: "Église", kr: "교회" },
  { cat: "Lieux & Transports", fr: "Marché", kr: "시장" },
  { cat: "Lieux & Transports", fr: "Supermarché", kr: "슈퍼마켓" },
  { cat: "Lieux & Transports", fr: "Hôtel", kr: "호텔" },
  { cat: "Lieux & Transports", fr: "Café (lieu)", kr: "카페" },
  { cat: "Lieux & Transports", fr: "Cinéma", kr: "영화관" },
  { cat: "Lieux & Transports", fr: "Bus", kr: "버스" },
  { cat: "Lieux & Transports", fr: "Train", kr: "기차" },
  { cat: "Lieux & Transports", fr: "Métro", kr: "지하철" },
  { cat: "Lieux & Transports", fr: "Taxi", kr: "택시" },
  { cat: "Lieux & Transports", fr: "Voiture", kr: "자동차" },
  { cat: "Lieux & Transports", fr: "Vélo", kr: "자전거" },
  { cat: "Lieux & Transports", fr: "Avion", kr: "비행기" },
  { cat: "Lieux & Transports", fr: "Bateau", kr: "배" },
  { cat: "Lieux & Transports", fr: "Moto", kr: "오토바이" },
  { cat: "Lieux & Transports", fr: "À pied", kr: "걸어서" },
  { cat: "Lieux & Transports", fr: "Rue", kr: "길" },
  { cat: "Lieux & Transports", fr: "Pont", kr: "다리" },
  { cat: "Lieux & Transports", fr: "Parc", kr: "공원" },
  { cat: "Lieux & Transports", fr: "Plage", kr: "해변" },
  { cat: "Lieux & Transports", fr: "Montagne", kr: "산" },
  { cat: "Lieux & Transports", fr: "Rivière", kr: "강" },
  { cat: "Lieux & Transports", fr: "Mer", kr: "바다" },
  { cat: "Lieux & Transports", fr: "Quartier", kr: "동네" },
  { cat: "Lieux & Transports", fr: "Immeuble", kr: "건물" },
  { cat: "Lieux & Transports", fr: "Appartement", kr: "아파트" },
  { cat: "Lieux & Transports", fr: "Bureau", kr: "사무실" },
  { cat: "Lieux & Transports", fr: "Usine", kr: "공장" },
  { cat: "Lieux & Transports", fr: "Arrêt de bus", kr: "버스 정류장" },
  { cat: "Lieux & Transports", fr: "Station (métro)", kr: "지하철역" },
  { cat: "Lieux & Transports", fr: "Sortie", kr: "출구" },
  { cat: "Lieux & Transports", fr: "Entrée", kr: "입구" },
  { cat: "Lieux & Transports", fr: "Carrefour", kr: "교차로" },
  { cat: "Lieux & Transports", fr: "Feu de circulation", kr: "신호등" },
  { cat: "Lieux & Transports", fr: "Trottoir", kr: "인도" },
  { cat: "Lieux & Transports", fr: "Place (lieu)", kr: "광장" },
  { cat: "Lieux & Transports", fr: "Tour (bâtiment)", kr: "타워" },
  { cat: "Lieux & Transports", fr: "Frontière", kr: "국경" },
  { cat: "Lieux & Transports", fr: "Île", kr: "섬" },
  { cat: "Lieux & Transports", fr: "Village", kr: "마을" },

  // ---------- Verbes / Routine quotidienne ----------
  { cat: "Routine quotidienne", fr: "Voir", kr: "보다" },
  { cat: "Routine quotidienne", fr: "Venir", kr: "오다" },
  { cat: "Routine quotidienne", fr: "Aller", kr: "가다" },
  { cat: "Routine quotidienne", fr: "Donner", kr: "주다" },
  { cat: "Routine quotidienne", fr: "Se réveiller", kr: "일어나다" },
  { cat: "Routine quotidienne", fr: "Dormir", kr: "자다" },
  { cat: "Routine quotidienne", fr: "Manger", kr: "먹다" },
  { cat: "Routine quotidienne", fr: "Boire", kr: "마시다" },
  { cat: "Routine quotidienne", fr: "Travailler", kr: "일하다" },
  { cat: "Routine quotidienne", fr: "Étudier", kr: "공부하다" },
  { cat: "Routine quotidienne", fr: "Se laver / doucher", kr: "씻다" },
  { cat: "Routine quotidienne", fr: "Se reposer", kr: "쉬다" },
  { cat: "Routine quotidienne", fr: "Rencontrer (qqn)", kr: "만나다" },
  { cat: "Routine quotidienne", fr: "Acheter", kr: "사다" },
  { cat: "Routine quotidienne", fr: "Lire", kr: "읽다" },
  { cat: "Routine quotidienne", fr: "Écrire", kr: "쓰다" },
  { cat: "Routine quotidienne", fr: "Écouter", kr: "듣다" },
  { cat: "Routine quotidienne", fr: "Parler", kr: "말하다" },
  { cat: "Routine quotidienne", fr: "Marcher", kr: "걷다" },
  { cat: "Routine quotidienne", fr: "Courir", kr: "뛰다" },
  { cat: "Routine quotidienne", fr: "Cuisiner", kr: "요리하다" },
  { cat: "Routine quotidienne", fr: "Nettoyer", kr: "청소하다" },
  { cat: "Routine quotidienne", fr: "Se brosser les dents", kr: "양치하다" },
  { cat: "Routine quotidienne", fr: "S'habiller", kr: "옷을 입다" },
  { cat: "Routine quotidienne", fr: "Se déshabiller", kr: "옷을 벗다" },
  { cat: "Routine quotidienne", fr: "Sortir", kr: "나가다" },
  { cat: "Routine quotidienne", fr: "Rentrer", kr: "돌아오다" },
  { cat: "Routine quotidienne", fr: "Commencer", kr: "시작하다" },
  { cat: "Routine quotidienne", fr: "Finir / terminer", kr: "끝내다" },
  { cat: "Routine quotidienne", fr: "Attendre", kr: "기다리다" },
  { cat: "Routine quotidienne", fr: "Conduire", kr: "운전하다" },
  { cat: "Routine quotidienne", fr: "Envoyer", kr: "보내다" },
  { cat: "Routine quotidienne", fr: "Recevoir", kr: "받다" },
  { cat: "Routine quotidienne", fr: "Appeler (téléphoner)", kr: "전화하다" },
  { cat: "Routine quotidienne", fr: "Répondre", kr: "대답하다" },
  { cat: "Routine quotidienne", fr: "Demander", kr: "물어보다" },
  { cat: "Routine quotidienne", fr: "Penser", kr: "생각하다" },
  { cat: "Routine quotidienne", fr: "Choisir", kr: "고르다" },
  { cat: "Routine quotidienne", fr: "Payer", kr: "지불하다" },
  { cat: "Routine quotidienne", fr: "Vendre", kr: "팔다" },
  { cat: "Routine quotidienne", fr: "Apprendre", kr: "배우다" },
  { cat: "Routine quotidienne", fr: "Enseigner", kr: "가르치다" },
  { cat: "Routine quotidienne", fr: "Jouer", kr: "놀다" },
  { cat: "Routine quotidienne", fr: "Chanter", kr: "노래하다" },
  { cat: "Routine quotidienne", fr: "Danser", kr: "춤추다" },
  { cat: "Routine quotidienne", fr: "Rire", kr: "웃다" },
  { cat: "Routine quotidienne", fr: "Pleurer", kr: "울다" },
  { cat: "Routine quotidienne", fr: "Se dépêcher", kr: "서두르다" },
  { cat: "Routine quotidienne", fr: "Se lever (du lit)", kr: "일어서다" },
  { cat: "Routine quotidienne", fr: "S'asseoir", kr: "앉다" },
  { cat: "Routine quotidienne", fr: "Ouvrir", kr: "열다" },
  { cat: "Routine quotidienne", fr: "Fermer", kr: "닫다" },
  { cat: "Routine quotidienne", fr: "Allumer", kr: "켜다" },
  { cat: "Routine quotidienne", fr: "Éteindre", kr: "끄다" },

  // ---------- Nourriture & Boissons ----------
  { cat: "Nourriture & Boissons", fr: "Viande", kr: "고기" },
  { cat: "Nourriture & Boissons", fr: "Légume", kr: "채소" },
  { cat: "Nourriture & Boissons", fr: "Fruit", kr: "과일" },
  { cat: "Nourriture & Boissons", fr: "Alcool", kr: "술" },
  { cat: "Nourriture & Boissons", fr: "Riz / repas", kr: "밥" },
  { cat: "Nourriture & Boissons", fr: "Eau", kr: "물" },
  { cat: "Nourriture & Boissons", fr: "Café", kr: "커피" },
  { cat: "Nourriture & Boissons", fr: "Thé", kr: "차" },
  { cat: "Nourriture & Boissons", fr: "Soupe", kr: "국" },
  { cat: "Nourriture & Boissons", fr: "Nouilles", kr: "면" },
  { cat: "Nourriture & Boissons", fr: "Poisson", kr: "생선" },
  { cat: "Nourriture & Boissons", fr: "Œuf", kr: "달걀" },
  { cat: "Nourriture & Boissons", fr: "Pain", kr: "빵" },
  { cat: "Nourriture & Boissons", fr: "Lait", kr: "우유" },
  { cat: "Nourriture & Boissons", fr: "Poulet", kr: "닭고기" },
  { cat: "Nourriture & Boissons", fr: "Bœuf", kr: "소고기" },
  { cat: "Nourriture & Boissons", fr: "Porc", kr: "돼지고기" },
  { cat: "Nourriture & Boissons", fr: "Riz cuit", kr: "쌀밥" },
  { cat: "Nourriture & Boissons", fr: "Kimchi", kr: "김치" },
  { cat: "Nourriture & Boissons", fr: "Sauce soja", kr: "간장" },
  { cat: "Nourriture & Boissons", fr: "Sucre", kr: "설탕" },
  { cat: "Nourriture & Boissons", fr: "Sel", kr: "소금" },
  { cat: "Nourriture & Boissons", fr: "Poivre", kr: "후추" },
  { cat: "Nourriture & Boissons", fr: "Huile", kr: "기름" },
  { cat: "Nourriture & Boissons", fr: "Fromage", kr: "치즈" },
  { cat: "Nourriture & Boissons", fr: "Beurre", kr: "버터" },
  { cat: "Nourriture & Boissons", fr: "Gâteau", kr: "케이크" },
  { cat: "Nourriture & Boissons", fr: "Bonbon", kr: "사탕" },
  { cat: "Nourriture & Boissons", fr: "Chocolat", kr: "초콜릿" },
  { cat: "Nourriture & Boissons", fr: "Glace (dessert)", kr: "아이스크림" },
  { cat: "Nourriture & Boissons", fr: "Jus", kr: "주스" },
  { cat: "Nourriture & Boissons", fr: "Soda", kr: "탄산음료" },
  { cat: "Nourriture & Boissons", fr: "Bière", kr: "맥주" },
  { cat: "Nourriture & Boissons", fr: "Vin", kr: "와인" },
  { cat: "Nourriture & Boissons", fr: "Soju", kr: "소주" },
  { cat: "Nourriture & Boissons", fr: "Pomme", kr: "사과" },
  { cat: "Nourriture & Boissons", fr: "Banane", kr: "바나나" },
  { cat: "Nourriture & Boissons", fr: "Raisin", kr: "포도" },
  { cat: "Nourriture & Boissons", fr: "Fraise", kr: "딸기" },
  { cat: "Nourriture & Boissons", fr: "Pastèque", kr: "수박" },
  { cat: "Nourriture & Boissons", fr: "Carotte", kr: "당근" },
  { cat: "Nourriture & Boissons", fr: "Pomme de terre", kr: "감자" },
  { cat: "Nourriture & Boissons", fr: "Oignon", kr: "양파" },
  { cat: "Nourriture & Boissons", fr: "Ail", kr: "마늘" },
  { cat: "Nourriture & Boissons", fr: "Tomate", kr: "토마토" },
  { cat: "Nourriture & Boissons", fr: "Champignon", kr: "버섯" },
  { cat: "Nourriture & Boissons", fr: "Tofu", kr: "두부" },
  { cat: "Nourriture & Boissons", fr: "Soupe épicée", kr: "찌개" },
  { cat: "Nourriture & Boissons", fr: "Petit-déjeuner", kr: "아침밥" },
  { cat: "Nourriture & Boissons", fr: "Déjeuner", kr: "점심밥" },
  { cat: "Nourriture & Boissons", fr: "Dîner", kr: "저녁밥" },
  { cat: "Nourriture & Boissons", fr: "Dessert", kr: "디저트" },
  { cat: "Nourriture & Boissons", fr: "Collation", kr: "간식" },
  { cat: "Nourriture & Boissons", fr: "Restaurant (resto)", kr: "음식점" },

  // ---------- Corps & Santé ----------
  { cat: "Corps & Santé", fr: "Tête", kr: "머리" },
  { cat: "Corps & Santé", fr: "Visage", kr: "얼굴" },
  { cat: "Corps & Santé", fr: "Œil", kr: "눈" },
  { cat: "Corps & Santé", fr: "Nez", kr: "코" },
  { cat: "Corps & Santé", fr: "Bouche", kr: "입" },
  { cat: "Corps & Santé", fr: "Oreille", kr: "귀" },
  { cat: "Corps & Santé", fr: "Cou", kr: "목" },
  { cat: "Corps & Santé", fr: "Épaule", kr: "어깨" },
  { cat: "Corps & Santé", fr: "Bras", kr: "팔" },
  { cat: "Corps & Santé", fr: "Main", kr: "손" },
  { cat: "Corps & Santé", fr: "Doigt", kr: "손가락" },
  { cat: "Corps & Santé", fr: "Jambe", kr: "다리" },
  { cat: "Corps & Santé", fr: "Pied", kr: "발" },
  { cat: "Corps & Santé", fr: "Dos", kr: "등" },
  { cat: "Corps & Santé", fr: "Ventre", kr: "배" },
  { cat: "Corps & Santé", fr: "Cœur (organe)", kr: "심장" },
  { cat: "Corps & Santé", fr: "Dent", kr: "이" },
  { cat: "Corps & Santé", fr: "Cheveux", kr: "머리카락" },
  { cat: "Corps & Santé", fr: "Peau", kr: "피부" },
  { cat: "Corps & Santé", fr: "Os", kr: "뼈" },
  { cat: "Corps & Santé", fr: "Sang", kr: "피" },
  { cat: "Corps & Santé", fr: "Être malade", kr: "아프다" },
  { cat: "Corps & Santé", fr: "Avoir mal à la tête", kr: "머리가 아프다" },
  { cat: "Corps & Santé", fr: "Avoir mal au ventre", kr: "배가 아프다" },
  { cat: "Corps & Santé", fr: "Fièvre", kr: "열" },
  { cat: "Corps & Santé", fr: "Toux", kr: "기침" },
  { cat: "Corps & Santé", fr: "Rhume", kr: "감기" },
  { cat: "Corps & Santé", fr: "Médicament", kr: "약" },
  { cat: "Corps & Santé", fr: "Médecin", kr: "의사" },
  { cat: "Corps & Santé", fr: "Infirmier/ère", kr: "간호사" },
  { cat: "Corps & Santé", fr: "Douleur", kr: "통증" },
  { cat: "Corps & Santé", fr: "Blessure", kr: "상처" },
  { cat: "Corps & Santé", fr: "Allergie", kr: "알레르기" },
  { cat: "Corps & Santé", fr: "Vaccin", kr: "백신" },
  { cat: "Corps & Santé", fr: "Être en bonne santé", kr: "건강하다" },
  { cat: "Corps & Santé", fr: "Être fatigué", kr: "피곤하다" },
  { cat: "Corps & Santé", fr: "Se sentir bien", kr: "괜찮다" },
  { cat: "Corps & Santé", fr: "Vomir", kr: "토하다" },
  { cat: "Corps & Santé", fr: "Vertige", kr: "현기증" },
  { cat: "Corps & Santé", fr: "Stress", kr: "스트레스" },
  { cat: "Corps & Santé", fr: "Régime alimentaire", kr: "다이어트" },
  { cat: "Corps & Santé", fr: "Exercice physique", kr: "운동" },
  { cat: "Corps & Santé", fr: "Sommeil", kr: "수면" },
  { cat: "Corps & Santé", fr: "Poids", kr: "몸무게" },
  { cat: "Corps & Santé", fr: "Taille (hauteur)", kr: "키" },
  { cat: "Corps & Santé", fr: "Respirer", kr: "숨을 쉬다" },
  { cat: "Corps & Santé", fr: "Se blesser", kr: "다치다" },
  { cat: "Corps & Santé", fr: "Guérir", kr: "낫다" },
  { cat: "Corps & Santé", fr: "Ordonnance", kr: "처방전" },

  // ---------- Animaux ----------
  { cat: "Animaux", fr: "Chien", kr: "개" },
  { cat: "Animaux", fr: "Chat", kr: "고양이" },
  { cat: "Animaux", fr: "Oiseau", kr: "새" },
  { cat: "Animaux", fr: "Poisson (animal)", kr: "물고기" },
  { cat: "Animaux", fr: "Cheval", kr: "말" },
  { cat: "Animaux", fr: "Vache", kr: "소" },
  { cat: "Animaux", fr: "Cochon", kr: "돼지" },
  { cat: "Animaux", fr: "Mouton", kr: "양" },
  { cat: "Animaux", fr: "Lapin", kr: "토끼" },
  { cat: "Animaux", fr: "Souris", kr: "쥐" },
  { cat: "Animaux", fr: "Tigre", kr: "호랑이" },
  { cat: "Animaux", fr: "Lion", kr: "사자" },
  { cat: "Animaux", fr: "Ours", kr: "곰" },
  { cat: "Animaux", fr: "Singe", kr: "원숭이" },
  { cat: "Animaux", fr: "Éléphant", kr: "코끼리" },
  { cat: "Animaux", fr: "Serpent", kr: "뱀" },
  { cat: "Animaux", fr: "Grenouille", kr: "개구리" },
  { cat: "Animaux", fr: "Insecte", kr: "곤충" },
  { cat: "Animaux", fr: "Papillon", kr: "나비" },
  { cat: "Animaux", fr: "Abeille", kr: "벌" },

  // ---------- Sensations & Émotions ----------
  { cat: "Sensations & Émotions", fr: "Être content / heureux", kr: "기쁘다" },
  { cat: "Sensations & Émotions", fr: "Être triste", kr: "슬프다" },
  { cat: "Sensations & Émotions", fr: "Être en colère", kr: "화나다" },
  { cat: "Sensations & Émotions", fr: "Avoir peur", kr: "무섭다" },
  { cat: "Sensations & Émotions", fr: "Être surpris", kr: "놀랍다" },
  { cat: "Sensations & Émotions", fr: "Être ennuyé(e) / s'ennuyer", kr: "지루하다" },
  { cat: "Sensations & Émotions", fr: "Être inquiet", kr: "걱정되다" },
  { cat: "Sensations & Émotions", fr: "Être nerveux", kr: "긴장되다" },
  { cat: "Sensations & Émotions", fr: "Être gêné / embarrassé", kr: "당황스럽다" },
  { cat: "Sensations & Émotions", fr: "Être fier", kr: "자랑스럽다" },
  { cat: "Sensations & Émotions", fr: "Avoir faim", kr: "배고프다" },
  { cat: "Sensations & Émotions", fr: "Être rassasié / plein", kr: "배부르다" },
  { cat: "Sensations & Émotions", fr: "Avoir soif", kr: "목마르다" },
  { cat: "Sensations & Émotions", fr: "Être fatigué (sensation)", kr: "지치다" },
  { cat: "Sensations & Émotions", fr: "Avoir sommeil", kr: "졽리다" },
  { cat: "Sensations & Émotions", fr: "Avoir froid", kr: "춥다" },
  { cat: "Sensations & Émotions", fr: "Avoir chaud", kr: "덥다" },
  { cat: "Sensations & Émotions", fr: "Être confortable / à l'aise", kr: "편하다" },
  { cat: "Sensations & Émotions", fr: "Être mal à l'aise / inconfortable", kr: "불편하다" },
  { cat: "Sensations & Émotions", fr: "Aimer (qqch/qqn)", kr: "좋아하다" },
  { cat: "Sensations & Émotions", fr: "Détester / ne pas aimer", kr: "싫어하다" },
  { cat: "Sensations & Émotions", fr: "Être amusant / drôle", kr: "재미있다" },
  { cat: "Sensations & Émotions", fr: "Être ennuyeux (chose)", kr: "재미없다" },
  { cat: "Sensations & Émotions", fr: "Être jaloux", kr: "질투하다" },
  { cat: "Sensations & Émotions", fr: "Être seul", kr: "외롭다" },
  { cat: "Sensations & Émotions", fr: "Être soulagé", kr: "안심되다" },
  { cat: "Sensations & Émotions", fr: "Être déçu", kr: "실망하다" },
  { cat: "Sensations & Émotions", fr: "Être reconnaissant", kr: "고맙다" },
  { cat: "Sensations & Émotions", fr: "Avoir honte", kr: "부끄럽다" },
  { cat: "Sensations & Émotions", fr: "Être excité / impatient", kr: "신나다" },

  // ---------- Technologie & Loisirs ----------
  { cat: "Technologie & Loisirs", fr: "Téléphone", kr: "전화기" },
  { cat: "Technologie & Loisirs", fr: "Ordinateur", kr: "컴퓨터" },
  { cat: "Technologie & Loisirs", fr: "Internet", kr: "인터넷" },
  { cat: "Technologie & Loisirs", fr: "Application", kr: "앱" },
  { cat: "Technologie & Loisirs", fr: "Photo", kr: "사진" },
  { cat: "Technologie & Loisirs", fr: "Vidéo", kr: "영상" },
  { cat: "Technologie & Loisirs", fr: "Jeu (vidéo)", kr: "게임" },
  { cat: "Technologie & Loisirs", fr: "Musique", kr: "음악" },
  { cat: "Technologie & Loisirs", fr: "Film", kr: "영화" },
  { cat: "Technologie & Loisirs", fr: "Livre", kr: "책" },
  { cat: "Technologie & Loisirs", fr: "Télévision", kr: "텔레비전" },
  { cat: "Technologie & Loisirs", fr: "Réseaux sociaux", kr: "소셜 미디어" },
  { cat: "Technologie & Loisirs", fr: "Message", kr: "문자" },
  { cat: "Technologie & Loisirs", fr: "Caméra", kr: "카메라" },
  { cat: "Technologie & Loisirs", fr: "Écouteurs", kr: "이어폰" },
  { cat: "Technologie & Loisirs", fr: "Batterie", kr: "배터리" },
  { cat: "Technologie & Loisirs", fr: "Wifi", kr: "와이파이" },
  { cat: "Technologie & Loisirs", fr: "Sport (loisir)", kr: "운동" },
  { cat: "Technologie & Loisirs", fr: "Voyage", kr: "여행" },
  { cat: "Technologie & Loisirs", fr: "Photographie (loisir)", kr: "사진 찍기" },

];

/* ===================================================================
   VOCABULAIRE — ANGLAIS
   Même structure que koreanData. Vide pour l'instant : ajoute tes
   propres entrées ici, par ex :
   { cat: "Salutations", fr: "Bonjour", kr: "Hello" },
   (le champ s'appelle "kr" pour rester compatible avec le moteur
   d'affichage, mais il contient simplement le mot anglais)
=================================================================== */
const englishData = [

];
