/* ===================================================================
   PHRASES — banque pour l'activité "Phrase à trous"
   Chaque phrase a : le texte coréen complet (sentence), sa traduction
   française (fr), et le mot exact à faire deviner (blank — doit
   apparaître tel quel dans `sentence`).
   Pour ajouter une phrase : copie une ligne et adapte.
=================================================================== */

const sentenceBank = [
  { sentence: "내일 식당 가요", fr: "Je vais au restaurant demain", blank: "식당" },
  { sentence: "지금 학교 가요", fr: "Je vais à l'école maintenant", blank: "학교" },
  { sentence: "고기 맛있다", fr: "La viande est délicieuse", blank: "고기" },
  { sentence: "과일 조금 먹어요", fr: "Je mange un peu de fruits", blank: "과일" },
  { sentence: "어제 집에 있어요", fr: "Hier j'étais à la maison", blank: "집" },
  { sentence: "내일 아침 학교 가요", fr: "Demain matin je vais à l'école", blank: "아침" },
  { sentence: "식당 어디예요", fr: "Où est le restaurant ?", blank: "어디" },
  { sentence: "가게 얼마예요", fr: "Combien coûte le magasin ?", blank: "가게" },
  { sentence: "지금 점심 먹어요", fr: "Je mange à midi maintenant", blank: "점심" },
  { sentence: "내일 주말이에요", fr: "Demain c'est le week-end", blank: "주말" },
  { sentence: "물 주세요", fr: "De l'eau, s'il vous plaît", blank: "물" },
  { sentence: "커피 좋아해요", fr: "J'aime le café", blank: "커피" },
  { sentence: "고기 사요", fr: "J'achète de la viande", blank: "고기" },
  { sentence: "책 읽어요", fr: "Je lis un livre", blank: "책" },
  { sentence: "친구 만나요", fr: "Je rencontre un ami", blank: "친구" },
  { sentence: "버스 타요", fr: "Je prends le bus", blank: "버스" },
  { sentence: "병원 가요", fr: "Je vais à l'hôpital", blank: "병원" },
  { sentence: "음악 들어요", fr: "J'écoute de la musique", blank: "음악" },
  { sentence: "사진 찍어요", fr: "Je prends une photo", blank: "사진" },
  { sentence: "개 좋아해요", fr: "J'aime les chiens", blank: "개" },
  { sentence: "오늘 날씨 좋아요", fr: "Le temps est bon aujourd'hui", blank: "오늘" },
  { sentence: "기차역 가요", fr: "Je vais à la gare", blank: "기차역" },
  { sentence: "공항 가요", fr: "Je vais à l'aéroport", blank: "공항" },
  { sentence: "은행 가요", fr: "Je vais à la banque", blank: "은행" },
  { sentence: "약국 가요", fr: "Je vais à la pharmacie", blank: "약국" },
  { sentence: "도서관 가요", fr: "Je vais à la bibliothèque", blank: "도서관" },
  { sentence: "시장 가요", fr: "Je vais au marché", blank: "시장" },
  { sentence: "지하철 타요", fr: "Je prends le métro", blank: "지하철" },
  { sentence: "택시 타요", fr: "Je prends un taxi", blank: "택시" },
  { sentence: "자전거 타요", fr: "Je prends le vélo", blank: "자전거" },
  { sentence: "공원 가요", fr: "Je vais au parc", blank: "공원" },
  { sentence: "바다 좋아해요", fr: "J'aime la mer", blank: "바다" },
  { sentence: "산 좋아해요", fr: "J'aime la montagne", blank: "산" },
  { sentence: "아파트 좋아요", fr: "L'appartement est bien", blank: "아파트" },
  { sentence: "사무실 가요", fr: "Je vais au bureau", blank: "사무실" },
  { sentence: "일어나요 지금", fr: "Je me réveille maintenant", blank: "일어나요" },
  { sentence: "지금 자요", fr: "Je dors maintenant", blank: "자요" },
  { sentence: "밥 먹어요", fr: "Je mange du riz", blank: "밥" },
  { sentence: "물 마셔요", fr: "Je bois de l'eau", blank: "마셔요" },
  { sentence: "지금 일해요", fr: "Je travaille maintenant", blank: "일해요" },
  { sentence: "한국어 공부해요", fr: "J'étudie le coréen", blank: "공부해요" },
  { sentence: "지금 쉬어요", fr: "Je me repose maintenant", blank: "쉬어요" },
  { sentence: "옷 사요", fr: "J'achète des vêtements", blank: "사요" },
  { sentence: "책 사요", fr: "J'achète un livre", blank: "책" },
  { sentence: "편지 써요", fr: "J'écris une lettre", blank: "써요" },
  { sentence: "음악 좋아해요", fr: "J'aime la musique", blank: "음악" },
  { sentence: "천천히 걸어요", fr: "Je marche lentement", blank: "걸어요" },
  { sentence: "빨리 뛰어요", fr: "Je cours vite", blank: "뛰어요" },
  { sentence: "저녁 요리해요", fr: "Je cuisine le dîner", blank: "요리해요" },
  { sentence: "집 청소해요", fr: "Je nettoie la maison", blank: "청소해요" },
  { sentence: "아침 일찍 나가요", fr: "Je sors tôt le matin", blank: "나가요" },
  { sentence: "저녁에 돌아와요", fr: "Je rentre le soir", blank: "돌아와요" },
  { sentence: "수업 시작해요", fr: "Le cours commence", blank: "시작해요" },
  { sentence: "일 끝내요", fr: "Je termine le travail", blank: "끝내요" },
  { sentence: "여기서 기다려요", fr: "J'attends ici", blank: "기다려요" },
  { sentence: "차 운전해요", fr: "Je conduis la voiture", blank: "운전해요" },
  { sentence: "문자 보내요", fr: "J'envoie un message", blank: "보내요" },
  { sentence: "전화해요 지금", fr: "J'appelle maintenant", blank: "전화해요" },
  { sentence: "질문 물어봐요", fr: "Je pose une question", blank: "물어봐요" },
  { sentence: "사진 좋아해요", fr: "J'aime les photos", blank: "사진" },
  { sentence: "영화 봐요", fr: "Je regarde un film", blank: "영화" },
  { sentence: "노래해요 지금", fr: "Je chante maintenant", blank: "노래해요" },
  { sentence: "춤춰요 지금", fr: "Je danse maintenant", blank: "춤춰요" },
  { sentence: "많이 웃어요", fr: "Je ris beaucoup", blank: "웃어요" },
  { sentence: "문 열어요", fr: "J'ouvre la porte", blank: "열어요" },
  { sentence: "문 닫아요", fr: "Je ferme la porte", blank: "닫아요" },
  { sentence: "불 켜요", fr: "J'allume la lumière", blank: "켜요" },
  { sentence: "불 꺼요", fr: "J'éteins la lumière", blank: "꺼요" },
  { sentence: "강아지 좋아해요", fr: "J'aime les chiens", blank: "강아지" },
  { sentence: "고양이 좋아해요", fr: "J'aime les chats", blank: "고양이" },
  { sentence: "여행 좋아해요", fr: "J'aime voyager", blank: "여행" },
  { sentence: "고기 먹어요", fr: "Je mange de la viande", blank: "고기" },
  { sentence: "채소 먹어요", fr: "Je mange des légumes", blank: "채소" },
  { sentence: "과일 사요", fr: "J'achète des fruits", blank: "과일" },
  { sentence: "술 마셔요", fr: "Je bois de l'alcool", blank: "술" },
  { sentence: "커피 마셔요", fr: "Je bois du café", blank: "커피" },
  { sentence: "차 마셔요", fr: "Je bois du thé", blank: "차" },
  { sentence: "빵 먹어요", fr: "Je mange du pain", blank: "빵" },
  { sentence: "우유 마셔요", fr: "Je bois du lait", blank: "우유" },
  { sentence: "치즈 좋아해요", fr: "J'aime le fromage", blank: "치즈" },
  { sentence: "케이크 먹어요", fr: "Je mange un gâteau", blank: "케이크" },
  { sentence: "초콜릿 좋아해요", fr: "J'aime le chocolat", blank: "초콜릿" },
  { sentence: "주스 마셔요", fr: "Je bois un jus", blank: "주스" },
  { sentence: "맥주 마셔요", fr: "Je bois une bière", blank: "맥주" },
  { sentence: "사과 먹어요", fr: "Je mange une pomme", blank: "사과" },
  { sentence: "바나나 먹어요", fr: "Je mange une banane", blank: "바나나" },
  { sentence: "당근 좋아해요", fr: "J'aime les carottes", blank: "당근" },
  { sentence: "감자 먹어요", fr: "Je mange une pomme de terre", blank: "감자" },
  { sentence: "토마토 좋아해요", fr: "J'aime les tomates", blank: "토마토" },
  { sentence: "두부 먹어요", fr: "Je mange du tofu", blank: "두부" },
  { sentence: "찌개 먹어요", fr: "Je mange une soupe épicée", blank: "찌개" },
  { sentence: "머리 아파요", fr: "J'ai mal à la tête", blank: "머리" },
  { sentence: "배 아파요", fr: "J'ai mal au ventre", blank: "배" },
  { sentence: "손 씻어요", fr: "Je me lave les mains", blank: "손" },
  { sentence: "눈 아파요", fr: "J'ai mal aux yeux", blank: "눈" },
  { sentence: "약 먹어요", fr: "Je prends un médicament", blank: "약" },
  { sentence: "의사 만나요", fr: "Je rencontre un médecin", blank: "의사" },
  { sentence: "병원 가요 지금", fr: "Je vais à l'hôpital maintenant", blank: "병원" },
  { sentence: "오늘 피곤해요", fr: "Je suis fatigué aujourd'hui", blank: "피곤해요" },
  { sentence: "지금 배고파요", fr: "J'ai faim maintenant", blank: "배고파요" },
  { sentence: "오늘 기뻐요", fr: "Je suis content aujourd'hui", blank: "기뻐요" },
];